import Head from 'next/head'
import Header from 'components/Header'
import Banner from 'components/Banner'
import SmallCard from 'components/SmallCard';
import MediumCard from 'components/MediumCard';
import LargeCard from 'components/LargeCard';


export default function Home({ exploreData, cardsData }) {

  return (
    <>
      <div>
        <Head>
           <title>Airbnb Clone</title>
           <meta name="description" content="Generated by create next app" />
           <meta name="viewport" content="width=device-width, initial-scale=1" />
           <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <Banner/>
        {/* We set a max-w-7xl to the main section to make sure it stretches to a max width of 7xl */}
        {/* We set mx-auto to center item it */}
        {/* We set px-8 to make sure we have padding in smaller screens */}
        {/* On a smaller screen we set padding to 16px */}
        <main className='max-w-7xl mx-auto px-8 sm:px-16'>
          {/* Section 1 */}
          <section className='pt-6'>
            <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>
            {/* The cards section goes below, and we pull some data here from a server */}
            {/* We set by default grid to 1 as we design mobile first. When we hit the first sm breakpoint we set grid col to 2, and ect.. */}
            <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
              {exploreData?.map(({img, distance, location}) => (
                <SmallCard 
                key={img}
                img={img} 
                distance={distance} 
                location={location}  
                />
              ))}
            </div>
          </section>
          {/* Section 2 */}
          <section>
            <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
            {/* We use parenthesis after item to get a direct return */}
            {/* We are destructuring item, to img, and title so we don't have item.img or item.title and ect.. */}
            {/* We use optional chaining after the cardsData with a ? incase it isn't able to fetch our data */}
            {/* We wrap our Medium card and the .map in a div so that we can keep it centered in its area */}
            {/* We space out each element so they're not touching using space-x-3 */}
            {/* To Hide the scroll bar we'll use a tailwind plugin called tailwind scroll-bar-hide  */}
            {/* Once we install tailwind-scrollbar-hide we update our tailwind config.js file and require it in our plugins section */}
            {/* We add padding of 3 so when we hover it doesn't get cut out */}
            {/* We add a negative margin of 3 through -ml-3 so its centered more */}
            <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
              {cardsData.map( ({img, title}) => (
                 <MediumCard 
                   key={img}
                   img={img}
                   title={title}
                 />
              ))}
            </div>
          </section>

          <LargeCard 
            img='https://links.papareact.com/4cj'
            title='The Greatest Outdoors'
            description='Wishlists curated by Airbnb.'
            buttonText='Get Inspired'  
          />

        </main>
      </div>
    </>
  );
}


// Fetching our Data from our links
export async function getStaticProps() {
  const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G').then(
    (res) => res.json()
  ); 

  const cardsData = await fetch('https://www.jsonkeeper.com/b/VHHT').then(
    (res) => res.json()
  )

  return {
    props: {
      exploreData,
      cardsData
    }
  }

}
